/**
 * ZEKS Markets — Onchain Lending Mock Data
 *
 * ⚠️  DEV-ONLY MOCK DATA  ⚠️
 *
 * Every entry here is a placeholder. Real values arrive from
 * Morpho + Robinhood + Chainlink in later phases.
 *
 * Until then, rows render with `sourceMode: "mock"` and the
 * page chrome surfaces a MOCK badge so users cannot mistake them
 * for live protocol metrics.
 *
 * DO NOT import this file from a React component directly. Always
 * go through `./service.ts` so the boundary stays enforced.
 */

import type { LendingMarket } from "./types"
import { ROBINHOOD_CHAIN_ID } from "../types"

export const MOCK_LENDING_MARKETS: LendingMarket[] = [
  {
    symbol: "AAPL",
    name: "Apple",
    logoUrl: "/assets/logos/AAPL.png",
    oraclePrice: 232.45,
    oracleSource: "mock",
    supplyApy: 4.32,
    borrowApy: 5.18,
    totalSupply: 18_420_000,
    totalBorrow: 9_640_000,
    availableLiquidity: 8_780_000,
    utilization: 52.33,
    tvl: 18_420_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "TSLA",
    name: "Tesla",
    logoUrl: "/assets/logos/TSLA.png",
    oraclePrice: 348.10,
    oracleSource: "mock",
    supplyApy: 5.71,
    borrowApy: 6.94,
    totalSupply: 12_080_000,
    totalBorrow: 7_210_000,
    availableLiquidity: 4_870_000,
    utilization: 59.69,
    tvl: 12_080_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    logoUrl: "/assets/logos/NVDA.png",
    oraclePrice: 138.62,
    oracleSource: "mock",
    supplyApy: 6.10,
    borrowApy: 7.45,
    totalSupply: 24_700_000,
    totalBorrow: 17_240_000,
    availableLiquidity: 7_460_000,
    utilization: 69.79,
    tvl: 24_700_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    logoUrl: "/assets/logos/MSFT.png",
    oraclePrice: 421.07,
    oracleSource: "mock",
    supplyApy: 3.84,
    borrowApy: 4.61,
    totalSupply: 9_980_000,
    totalBorrow: 4_220_000,
    availableLiquidity: 5_760_000,
    utilization: 42.28,
    tvl: 9_980_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "META",
    name: "Meta",
    logoUrl: "/assets/logos/META.png",
    oraclePrice: 562.94,
    oracleSource: "mock",
    supplyApy: 4.92,
    borrowApy: 5.85,
    totalSupply: 6_410_000,
    totalBorrow: 3_120_000,
    availableLiquidity: 3_290_000,
    utilization: 48.67,
    tvl: 6_410_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    logoUrl: "/assets/logos/AMZN.png",
    oraclePrice: 198.55,
    oracleSource: "mock",
    supplyApy: 4.05,
    borrowApy: 4.84,
    totalSupply: 7_520_000,
    totalBorrow: 3_640_000,
    availableLiquidity: 3_880_000,
    utilization: 48.40,
    tvl: 7_520_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    logoUrl: "/assets/logos/GOOGL.png",
    oraclePrice: 174.20,
    oracleSource: "mock",
    supplyApy: 4.41,
    borrowApy: 5.27,
    totalSupply: 5_180_000,
    totalBorrow: 2_410_000,
    availableLiquidity: 2_770_000,
    utilization: 46.53,
    tvl: 5_180_000,
    status: "active",
    protocolSource: "mock",
    sourceMode: "mock",
    contractAddress: null,
    marketId: null,
    collateralAssetSymbol: null,
    loanAssetSymbol: null,
    lltv: null,
    oracleAddress: null,
    irmAddress: null,
    loanTokenAddress: null,
    collateralTokenAddress: null,
    loanTokenDecimals: null,
    listed: null,
    rhContractAddress: null,
    rhMultiplier: null,
    rhTokenDecimals: null,
    rhLogoUrl: null,
    referenceBid: null,
    referenceAsk: null,
    referencePrice: null,
    referenceGeneratedAt: null,
    referenceIsHalt: false,
    chainId: ROBINHOOD_CHAIN_ID,
    fetchedAt: "",
  },
]
